name: Deployment

on:
  push:
    branches: [main]


jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: scripts/buildprod.sh